# Generated by Django 4.0.4 on 2022-11-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Addition', '+'), ('Subtraction', '-'), ('Division', '/')], default='Addition', max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Arit',
                'verbose_name_plural': 'Arit',
            },
        ),
    ]
