# Generated by Django 4.0.4 on 2022-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_arit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='arit',
            new_name='Solve',
        ),
        migrations.AlterModelOptions(
            name='solve',
            options={'verbose_name': 'Solve', 'verbose_name_plural': 'Solve'},
        ),
    ]
