# Generated by Django 4.0.4 on 2022-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_arit_solve_alter_solve_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='operation_type',
            field=models.CharField(max_length=100),
        ),
    ]
